# Generated by Django 2.2.5 on 2019-10-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('universo', models.CharField(max_length=100, verbose_name='Nome')),
                ('habilidade', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
    ]
